services:
  pg-source:
    image: postgres:14
    container_name: pg-source
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test@123
      POSTGRES_DB: source_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-source-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=4", "-c", "max_wal_senders=4"]

  pg-target:
    image: postgres:14
    container_name: pg-target
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test@123
      POSTGRES_DB: target_db
    volumes:
      - pg-target-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg-source-data:
  pg-target-data:
